// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	scheme "k8c.io/kubermatic/v2/pkg/crd/client/clientset/versioned/scheme"
	v1 "k8c.io/kubermatic/v2/pkg/crd/kubermatic/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EtcdRestoresGetter has a method to return a EtcdRestoreInterface.
// A group's client should implement this interface.
type EtcdRestoresGetter interface {
	EtcdRestores(namespace string) EtcdRestoreInterface
}

// EtcdRestoreInterface has methods to work with EtcdRestore resources.
type EtcdRestoreInterface interface {
	Create(*v1.EtcdRestore) (*v1.EtcdRestore, error)
	Update(*v1.EtcdRestore) (*v1.EtcdRestore, error)
	UpdateStatus(*v1.EtcdRestore) (*v1.EtcdRestore, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.EtcdRestore, error)
	List(opts metav1.ListOptions) (*v1.EtcdRestoreList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.EtcdRestore, err error)
	EtcdRestoreExpansion
}

// etcdRestores implements EtcdRestoreInterface
type etcdRestores struct {
	client rest.Interface
	ns     string
}

// newEtcdRestores returns a EtcdRestores
func newEtcdRestores(c *KubermaticV1Client, namespace string) *etcdRestores {
	return &etcdRestores{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the etcdRestore, and returns the corresponding etcdRestore object, and an error if there is any.
func (c *etcdRestores) Get(name string, options metav1.GetOptions) (result *v1.EtcdRestore, err error) {
	result = &v1.EtcdRestore{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("etcdrestores").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EtcdRestores that match those selectors.
func (c *etcdRestores) List(opts metav1.ListOptions) (result *v1.EtcdRestoreList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EtcdRestoreList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("etcdrestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested etcdRestores.
func (c *etcdRestores) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("etcdrestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a etcdRestore and creates it.  Returns the server's representation of the etcdRestore, and an error, if there is any.
func (c *etcdRestores) Create(etcdRestore *v1.EtcdRestore) (result *v1.EtcdRestore, err error) {
	result = &v1.EtcdRestore{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("etcdrestores").
		Body(etcdRestore).
		Do().
		Into(result)
	return
}

// Update takes the representation of a etcdRestore and updates it. Returns the server's representation of the etcdRestore, and an error, if there is any.
func (c *etcdRestores) Update(etcdRestore *v1.EtcdRestore) (result *v1.EtcdRestore, err error) {
	result = &v1.EtcdRestore{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("etcdrestores").
		Name(etcdRestore.Name).
		Body(etcdRestore).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *etcdRestores) UpdateStatus(etcdRestore *v1.EtcdRestore) (result *v1.EtcdRestore, err error) {
	result = &v1.EtcdRestore{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("etcdrestores").
		Name(etcdRestore.Name).
		SubResource("status").
		Body(etcdRestore).
		Do().
		Into(result)
	return
}

// Delete takes name of the etcdRestore and deletes it. Returns an error if one occurs.
func (c *etcdRestores) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("etcdrestores").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *etcdRestores) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("etcdrestores").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched etcdRestore.
func (c *etcdRestores) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.EtcdRestore, err error) {
	result = &v1.EtcdRestore{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("etcdrestores").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
