// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	scheme "github.com/kubermatic/kubermatic/pkg/crd/client/clientset/versioned/scheme"
	v1 "github.com/kubermatic/kubermatic/pkg/crd/kubermatic/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EtcdBackupsGetter has a method to return a EtcdBackupInterface.
// A group's client should implement this interface.
type EtcdBackupsGetter interface {
	EtcdBackups(namespace string) EtcdBackupInterface
}

// EtcdBackupInterface has methods to work with EtcdBackup resources.
type EtcdBackupInterface interface {
	Create(*v1.EtcdBackup) (*v1.EtcdBackup, error)
	Update(*v1.EtcdBackup) (*v1.EtcdBackup, error)
	UpdateStatus(*v1.EtcdBackup) (*v1.EtcdBackup, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.EtcdBackup, error)
	List(opts metav1.ListOptions) (*v1.EtcdBackupList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.EtcdBackup, err error)
	EtcdBackupExpansion
}

// etcdBackups implements EtcdBackupInterface
type etcdBackups struct {
	client rest.Interface
	ns     string
}

// newEtcdBackups returns a EtcdBackups
func newEtcdBackups(c *KubermaticV1Client, namespace string) *etcdBackups {
	return &etcdBackups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the etcdBackup, and returns the corresponding etcdBackup object, and an error if there is any.
func (c *etcdBackups) Get(name string, options metav1.GetOptions) (result *v1.EtcdBackup, err error) {
	result = &v1.EtcdBackup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("etcdbackups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EtcdBackups that match those selectors.
func (c *etcdBackups) List(opts metav1.ListOptions) (result *v1.EtcdBackupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EtcdBackupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("etcdbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested etcdBackups.
func (c *etcdBackups) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("etcdbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a etcdBackup and creates it.  Returns the server's representation of the etcdBackup, and an error, if there is any.
func (c *etcdBackups) Create(etcdBackup *v1.EtcdBackup) (result *v1.EtcdBackup, err error) {
	result = &v1.EtcdBackup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("etcdbackups").
		Body(etcdBackup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a etcdBackup and updates it. Returns the server's representation of the etcdBackup, and an error, if there is any.
func (c *etcdBackups) Update(etcdBackup *v1.EtcdBackup) (result *v1.EtcdBackup, err error) {
	result = &v1.EtcdBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("etcdbackups").
		Name(etcdBackup.Name).
		Body(etcdBackup).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *etcdBackups) UpdateStatus(etcdBackup *v1.EtcdBackup) (result *v1.EtcdBackup, err error) {
	result = &v1.EtcdBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("etcdbackups").
		Name(etcdBackup.Name).
		SubResource("status").
		Body(etcdBackup).
		Do().
		Into(result)
	return
}

// Delete takes name of the etcdBackup and deletes it. Returns an error if one occurs.
func (c *etcdBackups) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("etcdbackups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *etcdBackups) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("etcdbackups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched etcdBackup.
func (c *etcdBackups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.EtcdBackup, err error) {
	result = &v1.EtcdBackup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("etcdbackups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
